
- SVM:
```{r}
library(e1071)
library(kernlab)

data=read.csv("D:/Pinsker/MSCA/Time_Series/Project/advertising-and-sales-data.csv")
data=data[,2:3]
data$Month=rep(1:12,3)

data=ts(data, start=c(1980,1), frequency=12)

model7.svm.1 = svm(Sales ~ Advertising, data=data)
model7.svm.2 = svm(Sales ~ Advertising +factor(Month), data=data)

model7.svm.3=ksvm(Sales ~ Advertising, data=data, type = "nu-svr", kernel="rbfdot", C=2, prob.model=TRUE)


# Q-Q plots
qqnorm(residuals(model7.svm.1))
qqline(residuals(model7.svm.1))

qqnorm(residuals(model7.svm.2))
qqline(residuals(model7.svm.2))

# ACF PACF
tsdisplay(residuals(model7.svm.1))
tsdisplay(residuals(model7.svm.2))

# Ljung-Box test for the residuals
Box.test(residuals(model7.svm.1),fitdf=1,lag=20,type="Ljung")
Box.test(residuals(model7.svm.2),fitdf=2,lag=20,type="Ljung")

# Durbin-Watson test
durbinWatsonTest(as.vector(residuals(model7.svm.1)), alternative=c("two.sided"))
durbinWatsonTest(as.vector(residuals(model7.svm.2)), alternative=c("two.sided"))

# Forecast
## actual values
ts.plot(ts(data$Sales, start=c(1980,1), frequency=12), ylab="Sales", type="b", ylim=c(0,90))

## fitted values using SVM model
lines(ts(fitted(model.svm.1), start=c(1980,1), frequency=12), col="magenta", lwd=2)
lines(ts(fitted(model.svm.2), start=c(1980,1), frequency=12), col="blue", lwd=2)

legend("topleft",
       legend=c("actual values","fitted values using SVM1", "fitted values using SVM2"),
       col=c("black","magenta","blue"),lwd=1,bty='n',cex=0.7)

```

- TS-CV for model.svm.2:
```{r}
data=read.csv("D:/Pinsker/MSCA/Time_Series/Project/advertising-and-sales-data.csv")
data=data[,2:3]
data$Month=rep(1:12,3)

k = 18 # minimum data length for fitting a model
n = nrow(data)
mae.svm2 <- matrix(NA,n-k,12)

tmp.data=ts(data, start=c(1980,1), frequency=12)
st = tsp(tmp.data)[1]+(k-2)/12

for(i in 1:(n-k))
{
  #xshort <- window(data, start=st+(i-k+1)/12, end=st+i/12) # fixed window
  xshort <- window(tmp.data, end=st+i/12)
  xnext  <- window(tmp.data, start=st+(i+1)/12, end=st+(i+12)/12)
  xlong  <- window(tmp.data, end=st+(i+12)/12)
  
  # Model 1 w/ ARIMA(0,1,1) errors
  fit1   <- svm(Sales ~ Advertising + factor(Month), data=xshort)
  fcast.start = nrow(xshort) + 1
  fcast.end = nrow(xlong)
  fcast1 <- predict(fit1, xlong)[fcast.start:fcast.end]
    
  
  ts(mod7.predictor(model$model7, xshort, xnext, xlong), start=1, frequency=12)
  
  mae.svm2[i,1:nrow(xnext)] <- abs(fcast1-xnext[,2])
}

plot(1:12, sqrt(colMeans(mae1^2,na.rm=TRUE)), type="l", col=2, xlab="horizon", ylab="RMSE of Forecasting", ylim=c(10,25))
lines(1:12, sqrt(colMeans(mae1.rf^2,na.rm=TRUE)), type="o", lty=2, col="red")
lines(1:12, sqrt(colMeans(mae2^2,na.rm=TRUE)), type="l", col="blue")
lines(1:12, sqrt(colMeans(mae2.rf^2,na.rm=TRUE)), type="o", lty=2, col="blue")
lines(1:12, sqrt(colMeans(mae3^2,na.rm=TRUE)), type="l", col="orange", lwd=2)
lines(1:12, sqrt(colMeans(mae.svm2^2,na.rm=TRUE)), type="o", lty=2, col="magenta", lwd=2)

legend("topleft",legend=c("Model 1","Model 1 (using Random Forest, ntree=500)","Model 2","Model 2 (using Random Forest)","Model3 (Model 1 w/ ARIMA(0,1,1) errors)","SVM model"), col=c("red","red","blue","blue","orange","magenta"), lty=1, cex=0.7, bty="n")

```

